### ISSUE TITLE
Windows does not have an unzip tool for auto-installation (?)

### ISSUE THREAD

**Issue by koplenov** [vlang/vab#105]
**OS:**
* Windows 10 (1909)

**V version**
* V 0.2.2 92f19f5

**vab doctor**
```PowerShell
V panic: string index out of range: 1 / 1
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:8587: at v_panic: Backtrace
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:11725: by string_at
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:13358: by os__is_abs_path
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:13318: by os__find_abs_path_of_executable
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:22038: by vxt__vexe
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:29175: by main__check_essentials
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:29019: by main__main
C:/Users/koplenov/AppData/Local/Temp/v/vab.1399224875655115396.tmp.c:29845: by wmain
004f3a38 : by ???
004f3b9b : by ???
7ffddf237c24 : by ???
```

**What did you do?**
> vab install auto

**What did you expect to see?**
Auto install complete :))

**What did you see instead?**
```PowerShell
C:\DevSource\vab>vab.exe install auto
unzip failed with return code 2
exec failed (CreateProcess) with code 2: Cannot find the specified file.
 cmd: unzip C:\Users\koplenov\AppData\Local\Temp\v-android-sdk-cmdltools.tmp.zip -d C:\Users\koplenov\.cache\v\android\sdk\cmdline-tools
```

Is it because there was no provision for auto-installation on Windows systems?
I have no 'unzip' tool :D

**Comment by koplenov** [comment]
What if use https://modules.vlang.io/szip.html

**Comment by Larpon** [comment]
As stated in the [README](https://github.com/vlang/vab#install) currently only macOS and Linux hosts are supported. When I started developing `vab` szip was broken - I know it has been patched since but haven't had time to look at it. We gladly accept PRs with fixes to this!
[Code goes here](https://github.com/vlang/vab/blob/2bf56ef9159c2b6486b3069b32dde7751312f6c9/android/util/util.v#L86).

I'm closing this since Windows isn't officially supported (yet) and developers are aware that zip doesn't come preinstalled on Windows.
